baseurl = "https://docs.gitea.io/"
languageCode = "en-us"
title = "Docs"
theme = "gitea"
disqusShortname = "gitea"
disableRSS = false
disableSitemap = false

defaultContentLanguage = "en-us"
defaultContentLanguageInSubdir = true

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[params]
  Description = "Git with a cup of tea"
  Author = "The Gitea Authors"
  Website = "https://docs.gitea.io"
  Toplink = "docs"

[languages]
  [languages.en-us]
    weight = 0
  [languages.zh-cn]
    weight = 1
